<?php
/** @var \Amasty\MegaMenuLite\Block\Container $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Amasty\MegaMenuLite\ViewModel\Store\Menu $viewModel
 */

$viewModel = $block->getViewModel();
?>

<section class="ammenu-menu-wrapper"
         data-bind="
            scope: 'ammenu_wrapper',
            mageInit: {
                'Magento_Ui/js/core/app': {
                    components: {
                        'ammenu_wrapper': {
                            component: 'Amasty_MegaMenuLite/js/wrapper',
                            data: <?= $escaper->escapeHtml($block->getJsData()) ?>,
                            config: <?= $escaper->escapeHtml($block->getSerializedJsConfig()) ?>,
                            children: <?= $escaper->escapeHtml($block->getJsComponents()) ?>,
                            settings: <?= $escaper->escapeHtml($block->getJsSettings()) ?>,
                            links: <?= $escaper->escapeHtml($block->getStoreLinks()) ?>,
                            isMobile: <?= (int) $viewModel->isMobile() ?>
                        }
                    }
                }
            }">
    <?php // all conditionals removed to disable built-in 'on-load' mobile detect ?>
    <?php //if (!$viewModel->isHamburger() && !$viewModel->isMobile()): ?>
        <?= $block->getChildBlock('ammenu.top.menu')->setItems($block->getAllNodesData())->toHtml() ?>
    <?php //endif; ?>
    <?php //if ($viewModel->isHamburger() && !$viewModel->isMobile()): ?>
        <?= $block->getChildBlock('ammenu.top.menu')->setItems($block->getHamburgerNodesData())->toHtml() ?>
    <?php //endif; ?>
    <?php //if ($viewModel->isHamburger() || $viewModel->isMobile()): ?>
        <!-- ko scope: 'index = ammenu_sidebar_menu_wrapper' -->
            <!-- ko template: getTemplate() --><!-- /ko -->
        <!-- /ko -->
        <!-- ko scope: 'index = ammenu_overlay_wrapper' -->
            <!-- ko template: getTemplate() --><!-- /ko -->
        <!-- /ko -->
    <?php //endif; ?>
</section>
