stage:
    global:
        SKIP_HTML_MINIFICATION: true
        VERBOSE_COMMANDS: "-vv"
    build:
        SKIP_SCD: false
        SCD_STRATEGY: "compact"
        QUALITY_PATCHES:
          - MDVA-12304
    deploy:
        MYSQL_USE_SLAVE_CONNECTION: true
        REDIS_BACKEND: '\Magento\Framework\Cache\Backend\Redis'
    post-deploy:
        WARM_UP_PAGES:
            - "/"
            - "index.php"
            - "index.php/customer/account/create"
            - "index.php/chocolate-caramel"
            - "index.php/stoverssweetshoppemilkchocolatemelts"
            - "index.php/about-us"
