stage:
    global:
        VERBOSE_COMMANDS: "-vv"
    build:
        SCD_STRATEGY: "standard"
        QUALITY_PATCHES:
          - MDVA-12304
    deploy:
        MYSQL_USE_SLAVE_CONNECTION: true
    post-deploy:
        WARM_UP_PAGES:
            - "/"
            - "index.php"
            - "index.php/customer/account/create"
            - "index.php/chocolate-caramel"
            - "index.php/stoverssweetshoppemilkchocolatemelts"
            - "index.php/about-us"
