stage:
    global:
        VERBOSE_COMMANDS: "-vv"
    build:
        SKIP_SCD: false
        SCD_STRATEGY: "standard"
        QUALITY_PATCHES:
          - MDVA-12304
    deploy:
        MYSQL_USE_SLAVE_CONNECTION: true
#        CRON_CONSUMERS_RUNNER:
#            cron_run: true
#            max_messages: 1000
#            consumers: []
    post-deploy:
        WARM_UP_PAGES:
            - "/"
            - "index.php"
            - "index.php/customer/account/create"
            - "index.php/checkout/cart"
            - "index.php/checkout"
            - "index.php/chocolate-caramel"
            - "index.php/stoverssweetshoppemilkchocolatemelts"
            - "index.php/about-us"
