<?php
/** @var \Aheadworks\Blog\Block\Post\PrevNext $block */
/** @var \Aheadworks\Blog\ViewModel\Post $viewModel */

// @codingStandardsIgnoreFile
?>
<?php
$prevPost = $block->getPrevPost();
$nextPost = $block->getNextPost();
$viewModel = $block->getViewModel();
?>
<div class="block prev-next">
    <?php if ($prevPost): ?>
        <div class="prev-post-container">
            <div class="post-featured-title">
                <a href="<?= /* @noEscape */ $block->getPostUrl($prevPost) ?>" class="post-link">
                    <div><span class="post-arrow">&#8592;</span> <span><?= /* @noEscape */ __('PREVIOUS') ?></span></div>
                    <div><span><?= $block->escapeHtml($prevPost->getTitle()) ?></span></div>
                </a>
            </div>
            <?php if ($viewModel->isFeaturedImageLoaded($prevPost) || $viewModel->isPlaceholderImageLoaded()): ?>
                <a href="<?= /* @noEscape */ $block->getPostUrl($prevPost) ?>" class="post-featured-image-link">
                    <?= /* @noEscape */ $viewModel->getFeaturedImageHtml($block, 'aw_blog.prev_next_post_image', $prevPost)?>
                </a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <div class="delimiter"></div>
    <?php if ($nextPost): ?>
        <div class="next-post-container">
            <div class="post-featured-title">
                <a href="<?= /* @noEscape */ $block->getPostUrl($nextPost) ?>" class="post-link">
                    <div><span><?= /* @noEscape */ __('NEXT') ?></span> <span class="post-arrow">&#8594;</span></div>
                    <div><span><?= $block->escapeHtml($nextPost->getTitle()) ?></span></div>
                </a>
            </div>
            <?php if ($viewModel->isFeaturedImageLoaded($nextPost) || $viewModel->isPlaceholderImageLoaded()): ?>
                <a href="<?= /* @noEscape */ $block->getPostUrl($nextPost) ?>" class="post-featured-image-link">
                    <?= /* @noEscape */ $viewModel->getFeaturedImageHtml($block, 'aw_blog.prev_next_post_image', $nextPost)?>
                </a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
