<?php
/** @var \Aheadworks\Blog\Block\Post\RelatedPost $block */
/** @var \Aheadworks\Blog\ViewModel\Post $viewModel */

// @codingStandardsIgnoreFile
?>
<?php
    $posts = $block->getPosts();
    $viewModel = $block->getViewModel();
    $countPosts = count($posts);
    $clsGrid = '';
    if ($countPosts < 3) {
        $clsGrid = 'aw-one-posts';
    } elseif ($countPosts < 4) {
        $clsGrid = 'aw-three-posts';
    } elseif ($countPosts >= 4) {
        $clsGrid = 'aw-four-posts';
    } else {
        $clsGrid = '';
    }
?>
<?php if ($countPosts): ?>
    <div id="blog-related-posts" class="block">
        <div class="block-title">
            <strong class="blog-block-title"><?php echo $block->escapeHtml(__('Related Posts')) ?></strong>
        </div>
        <div class="block-content">
            <ul class="block-related-posts">
                <?php foreach ($posts as $post): ?>
                    <li class="block-related-posts-item <?= /* @noEscape */ $clsGrid;?>">
                        <?php if ($viewModel->isFeaturedImageLoaded($post) || $viewModel->isPlaceholderImageLoaded()): ?>
                            <a href="<?php /* @noEscape */ echo $block->escapeXssInUrl($block->getPostUrl($post)) ?>" class="related-post-featured-image-link">
                                <?= /* @noEscape */ $viewModel->getFeaturedImageHtml($block, 'aw_blog.related_post_image', $post)?>
                            </a>
                        <?php endif; ?>
                        <a href="<?php /* @noEscape */ echo $block->escapeXssInUrl($block->getPostUrl($post)) ?>"
                           class="block-related-post-link">
                            <?php echo $block->escapeHtml($post->getTitle()) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
