<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php
/** @var \HumanElement\OutOfStockRecommendations\Helper\Inventory $inventoryHelper */
$inventoryHelper = $this->helper(\HumanElement\OutOfStockRecommendations\Helper\Inventory::class);
$stockInfo = $inventoryHelper->getStockInfo($_product);
?>
<?php if (!$stockInfo->getIsAvailable()): ?>
    <div class="out-of-stock-recommendations">
        <p>Test Check</p>
    </div>
<?php endif; ?>
