<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php
/** @var \HumanElement\OutOfStockRecommendations\Helper\Inventory $inventoryHelper */
$inventoryHelper = $this->helper(\HumanElement\OutOfStockRecommendations\Helper\Inventory::class);
$stockInfo = $inventoryHelper->getStockInfo($_product);
?>
<?php if (!$stockInfo->getIsAvailable()): ?>
    <div class="out-of-stock-recommendations">
        <?php echo $this->getLayout()->createBlock("Magento\Catalog\Block\Product\View")->setTemplate("Magento_Catalog::product/out-of-stock-title.phtml")->toHtml();?>
        <?= ($this->getChildHtml('stock.catalog.product.related')) ?>
    </div>
<?php endif; ?>