<?php
use Aheadworks\Blog\Block\Post\Comment\Reply\Form;

/** @var Form $block */
?>

<div data-role="aw-blog-comment-reply-form-<?= $block->escapeHtmlAttr($block->getCommentId()) ?>"
     class="aw-blog__comment-reply-form"
     data-bind="scope: 'awBlogPostCommentReplyForm-<?= $block->escapeHtmlAttr($block->getCommentId()) ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=aw-blog-comment-reply-form-<?= $block->escapeHtmlAttr($block->getCommentId()) ?>]": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>

<?= /* @noEscape */ $block->getChildHtml('', false) ?>
