<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <div class="copyright-inner">
        <div class="copyright-links">
            <span><?= $block->escapeHtml($block->getCopyright()) ?></span><a href="/terms-of-use">Terms of Use</a><a href="/privacy-policy">Privacy Policy</a><a href="/digital-accessibility">Digital Accessibility</a><a href="/sitemap">Sitemap</a>
        </div>

        <div class="payment-icons">
            <span class="fab visa icon"></span><span class="fab mastercard icon"></span><span class="fab discover icon"></span><span class="fab americanExpress icon "></span><span class="fab applePay icon"></span><span class="fab amazonPay icon"></span><span class="fab payPal icon"></span>
        </div>
    </div>
</small>
