<div class="title">connect with us</div>
<div class="social-icons">
    <strong>Let's Be Friends</strong>
    <a href="https://www.instagram.com/stoverandcompany/" class="fab instagram"></a>
    <a href="https://www.facebook.com/StoverCompanyBaking/ " class="fab facebook"></a>
    <a href="https://twitter.com/StoverCoBaking " class="fab twitter"></a>
    <a href="https://www.youtube.com/channel/UCN6W8Zoy8pvxALTJ9hHwLWQ/featured " class="fab youtube"></a>
    <a href="https://www.pinterest.com/stovercompany/_created/" class="fab pinterest"></a>
</div>
