<div class="title">connect with us</div>
<div class="social-icons">
    <strong>Let's Be Friends</strong>
    <a href="https://www.instagram.com/stoverandcompany/" class="instagram"></a>
    <a href="https://www.facebook.com/StoverCompanyBaking/ " class="facebook"></a>
    <a href="https://twitter.com/StoverCoBaking " class="twitter"></a>
    <a href="https://www.youtube.com/channel/UCN6W8Zoy8pvxALTJ9hHwLWQ/featured " class="youtube"></a>
    <a href="https://www.pinterest.com/stovercompany/_created/" class="pinterest"></a>
</div>
