<?php
use Aheadworks\Blog\Block\Post\Comment\Form;

/** @var Form $block */
?>

<div data-role="aw-blog-comment-form"
     class="aw-blog-comment-form-wrapper <?= $block->isLoggedIn() ? 'logged-in' : '' ?>"
     data-bind="scope: 'awBlogCommentForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=aw-blog-comment-form]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
        }
    }
</script>

<?= /* @noEscape */ $block->getChildHtml('', false) ?>
