<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\Attributes */?>
<?php
$_product = $block->getProduct();
$dairyFree = $_product->getData('dairy_free');
$glutenFree = $_product->getData('gluten_free');
$kosher = $_product->getData('kosher');
$kosherDairy = $_product->getData('kosher_dairy');
$nonGMO = $_product->getData('non_gmo');
$peanutFree = $_product->getData('peanut_free');
?>
<?php if($dairyFree || $glutenFree || $kosher || $kosherDairy || $nonGMO || $peanutFree):?>
<div class="dietary-considerations-inner">
        <h2>dietary considerations</h2>
    <?php if($dairyFree): ?>
    <div class="dietary-icon dairy-free"></div>
    <?php endif;?>

    <?php if($glutenFree): ?>
    <div class="dietary-icon gluten-free"></div>

    <?php endif;?>

    <?php if($kosher): ?>
        <div class="dietary-icon kosher"></div>
    <?php endif;?>

    <?php if($kosherDairy): ?>
        <div class="dietary-icon kosher-dairy"></div>
    <?php endif;?>

    <?php if($nonGMO): ?>
    <div class="dietary-icon non-gmo"></div>
    <?php endif;?>
    <?php if($peanutFree): ?>
        <div class="dietary-icon peanut-free"></div>
    <?php endif;?>
</div>
<?php endif;?>