<?php

use Aheadworks\Blog\Block\Post;
use Aheadworks\Blog\ViewModel\Post as ViewModelPost;
use Magento\Framework\Escaper;

/* @var $block Post */
/* @var $viewModel ViewModelPost */
/* @var $escaper Escaper */
?>
<?php
$post = $block->getPost();
$viewModel = $block->getViewModel();
?>
<?php if ($post): ?>
    <article class="blog-posts-post blog-post">
        <header class="blog-post-header">
            <?php if ($block->isListItemMode()): ?>
                <h2 class="blog-post-title">
                    <a href="<?php /* @noEscape */ echo $escaper->escapeXssInUrl($block->getPostUrl($post)) ?>" class="blog-post-title-link">
                        <?php echo $escaper->escapeHtml($post->getTitle()) ?>
                    </a>
                </h2>
            <?php else: ?>
                <h1 class="blog-post-title"><?php echo $escaper->escapeHtml($post->getTitle()) ?></h1>
            <?php endif; ?>
            <ul class="blog-post-info">
                <?php if ($viewModel->getIsAuthorDisplayed($post)): ?>
                    <li class="blog-post-info-item">
                        <?php if ($block->isViewMode() && $post->getAuthor()->getImageFile()): ?>
                            <a class="author-image-link" href="<?= /* @noEscape */ $block->getAuthorUrl() ?>">
                                <img class="author-image"
                                     src="<?= $escaper->escapeUrl($block->getAuthorImageUrl()) ?>"
                                     title="<?= $escaper->escapeHtml($block->getAuthorFullname()) ?>"
                                     alt="<?= $escaper->escapeHtml($block->getAuthorImageAlt()) ?>"
                                />
                            </a>
                        <?php endif; ?>
                        <span class="inline-by"><?php /* @noEscape */ echo __('By ') ?></span>
                        <a class="author-link" href="<?= /* @noEscape */ $block->getAuthorUrl() ?>">
                            <?php /* @noEscape */ echo $block->getAuthorFullname() ?>
                        </a>
                    </li>
                <?php endif; ?>
                <li class="blog-post-info-item"><?php /* @noEscape */ echo $block->formatDate($post->getPublishDate(), \IntlDateFormatter::MEDIUM) ?></li>
                <?php if ($block->commentsEnabled()): ?>
                    <li class="blog-post-info-item">
                        <?php if ($block->getCommentType() === 'disqus'): ?>
                            <a href="#" data-url="<?php /* @noEscape */
                            echo $escaper->escapeXssInUrl($block->getPostUrl($post)) ?> #disqus_thread"
                               data-mage-init='{"blogCommentsLink": {}}' class="blog-post-info-comments">
                                <span class="blog-post-info-comments-icon"></span>
                                <span class="disqus-comment-count"
                                      data-disqus-identifier="<?php echo $escaper->escapeHtml($post->getId()) ?>"><?php /* @noEscape */
                                    echo __('0 Comments') ?></span>
                            </a>
                        <?php else: ?>
                            <a href="#" data-url="<?php /* @noEscape */
                            echo $escaper->escapeXssInUrl($block->getPostUrl($post)) ?> #builtin_thread"
                               data-mage-init='{"blogCommentsLink": {}}' class="blog-post-info-comments">
                                <span class="blog-post-info-comments-icon"></span>
                                <span class="builtin-comment-count"><?php /* @noEscape */ echo __($viewModel->getCommentsCount($post) . ' Comments') ?></span>
                            </a>
                        <?php endif; ?>
                    </li>
                <?php endif; ?>
                <?php if ($socialIconsHtml = $block->getSocialIconsHtml()): ?>
                    <li class="blog-post-info-item socialIcons">
                        <?php /* @noEscape */ echo $socialIconsHtml ?>
                    </li>
                <?php endif; ?>
            </ul>
        </header>
        <?php if ($viewModel->isFeaturedImageLoaded($post) || $viewModel->isPlaceholderImageLoaded()): ?>
            <div class="blog-post-featured-image-wrapper">
                <?php if ($block->isListItemMode()): ?>
                    <a href="<?php /* @noEscape */ echo $escaper->escapeXssInUrl($block->getPostUrl($post)) ?>" class="blog-post-featured-image-link">
                        <?= /* @noEscape */ $viewModel->getFeaturedImageHtml($block, 'aw_blog_post.post_image')?>
                    </a>
                <?php else: ?>
                    <?php if (empty($post->getFeaturedImageLink())): ?>
                            <?= /* @noEscape */ $viewModel->getFeaturedImageHtml($block, 'aw_blog_post.post_image')?>
                        <?php else: ?>
                            <a href="<?= /* @noEscape */ $escaper->escapeXssInUrl($post->getFeaturedImageLink()) ?>" target="_blank" class="blog-post-featured-image-link">
                                <?= /* @noEscape */ $viewModel->getFeaturedImageHtml($block, 'aw_blog_post.post_image')?>
                            </a>
                    <?php endif;?>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        <div class="blog-post-content">
            <?php /* @noEscape */ echo $block->getContent($post) ?>
        </div>
        <?php if ($block->showReadMoreButton($post)): ?>
            <p class="blog-post-read-more-wrapper">
                <a href="<?php /* @noEscape */ echo $escaper->escapeXssInUrl($block->getPostUrl($post)) ?>"
                   class="blog-post-read-more action">
                    <?php echo $escaper->escapeHtml(__('Read more')) ?>
                </a>
            </p>
        <?php endif; ?>
        <?php if ($block->isViewMode()): ?>
            <div class="blog-post-tags">
                <div class="blog-tags blog-tags-plain">
                    <?php foreach ($post->getTagNames() as $tagName): ?>
                        <a href="<?php /* @noEscape */ echo $escaper->escapeXssInUrl($block->getSearchByTagUrl($tagName)) ?>"
                           class="blog-tags-tag">
                            <?php echo $escaper->escapeHtml($tagName) ?>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php if ($socialIconsHtml = $block->getSocialIconsHtml()): ?>
                <div class="blog-post-share">
                    <p class="blog-post-share-title"><?php echo $escaper->escapeHtml(__('Share')) ?>:</p>
                    <div class="blog-post-share-content">
                        <div class="container">
                            <?php /* @noEscape */ echo $socialIconsHtml ?>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($viewModel->isNeedToDisplayAuthorBadgeBlock($post)): ?>
                <?= /* @noEscape */ $viewModel->renderAuthorBadgeHtml($block, $post) ?>
            <?php endif; ?>

        <?php endif; ?>
        <?php $categoryLinks = $block->getCategoryLinks() ?>
        <?php if ($linksCount = count($categoryLinks)): ?>
            <p class="blog-post-author">
                <?php echo $escaper->escapeHtml(__('Posted in')) ?>
                <?php if ($linksCount == 1): ?>
                    <?php /* @noEscape */ echo $categoryLinks[0] ?>
                <?php elseif ($linksCount == 2): ?>
                    <?php /* @noEscape */ echo __('%1 and %2', $categoryLinks[0], $categoryLinks[1]) ?>
                <?php elseif ($linksCount > 2): ?>
                    <?php /* @noEscape */ echo __(
                        '%1, %2 and %3',
                        implode(', ', array_slice($categoryLinks, 0, $linksCount - 2)), $categoryLinks[$linksCount - 2], $categoryLinks[$linksCount - 1]
                    ) ?>
                <?php endif; ?>
            </p>
        <?php endif; ?>
        <?php /* @noEscape */ echo $block->getPrevNextHtml($block->isViewMode()) ?>
        <?php /* @noEscape */ echo $block->getRelatedPostHtml($block->isViewMode()) ?>
        <?php /* @noEscape */ echo $block->getRelatedProductHtml($block->isViewMode(), $block->getPositionAfterPost()) ?>
        <?php if ($block->isViewMode() && $block->commentsEnabled()): ?>
            <?php /* @noEscape */ echo $block->getCommentEmbedHtml() ?>
        <?php endif; ?>
        <?php /* @noEscape */ echo $block->getRelatedProductHtml($block->isViewMode(), $block->getPositionAfterComments()) ?>
    </article>
<?php endif; ?>
