<?php
// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\Blog\Block\Adminhtml\Widget\Instance\Categories */
?>
<div class="widget-instance">
    <div id="<?= /* @noEscape */ $block->getId() ?>" class="tree-wrapper" data-mage-init='{"blogCategoryTree": <?= /* @noEscape */ $block->getConfig()?>}'>
        <div class="tree-actions">
            <a href="javascript:void(0);" class="collapse-tree-button"><?= /* @escapeNotVerified */ __('Collapse All') ?></a>
            <span class="separator">|</span>
            <a href="javascript:void(0);" class="expand-tree-button"><?= /* @escapeNotVerified */ __('Expand All') ?></a>
        </div>
        <div class="tree-init_<?= /* @noEscape */ $block->getId() ?>"></div>
    </div>
</div>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $('#<?= /* @noEscape */ $block->getId() ?>').trigger('contentUpdated')
    });
</script>
