<?php
use Aheadworks\Blog\Block\Email\Subscriber\Notification\Form;

/** @var Form $block */
?>

<div data-role="aw-blog-email-subscriber-notification-form"
     class="aw-blog__email-subscriber-notification-form"
     data-bind="scope: 'awBlogEmailSubscriberNotificationForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=aw-blog-email-subscriber-notification-form]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
        }
    }
</script>
