<?php $product = $block->getProduct(); ?>
<?php $preOrderDate = $product->getData('pre_order_date'); ?>

<?php if ($preOrderDate != "") : ?>
    <div class="product attribute pre_order_date">
        <div class="value_date">Estimated Ship Date: <b><?= date("m/d/Y", strtotime($preOrderDate)); ?></b></div>
        <div class="value_faq" itemprop="pre_order_date">Please see <a href="/faq" target="_blank">FAQ</a> Page for more information on <nobr>pre-order</nobr> products!</div>
    </div>
<?php endif; ?>