<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<style>
    h1 {font-size: 50px; color: #000; font-family: 'EBGaramond-Regular'; font-weight: 700; margin-bottom: 2.2rem;}
    p {color: #000; font-size: 1.6rem; font-family: 'Inter-Regular', 'Helvetica Neue', Helvetica, Arial, sans-serif;}
    a {color: #1C8276; font-weight: 700; text-decoration: none;}
</style>
<div style="text-align: center;">
    <img src="images/SC_Logo_Desktop_2x_1_1_.png" alt="Stover Company Logo"/>
    <h1>Service Temporarily Unavailable</h1>
    <p >We apologize for any inconvenience, but the website is under maintenance.  If you need immediate assistance please call our Customer Service
        <a href="tel:724.274.6314">724.274.6314</a>
    </p>
</div>
